In [4]:
import numpy as np
import json
import bgp_qnm_fits as bgp
import time
import pandas as pd

In [5]:
with open(f"PLT_results.json", "r") as f:
    PLT_results = json.load(f)

In [ ]:
# Convert the nested dictionary to a DataFrame
df = pd.DataFrame.from_dict(PLT_results, orient="index")

# Reset index to get the outer keys as a column
df = df.reset_index().rename(columns={"index": "PLT mode"})

df

,set,autocorrelation_times,percentile_90,n_iid_samples,n_steps,n_walkers,A_PLT_prior,T_PLT_prior,lam_PLT_prior
0,"(2,2)","[17.24593489, 19.75596196, 62.74109633]",0.000016,1394,5000,50,"[-0.1, 0.1]","[-50, 40]","[1, 15]"
1,"(3,3)","[14.97008348, 12.86091514, 53.58425786]",0.000012,1632,5000,50,"[-0.1, 0.1]","[-50, 40]","[1, 15]"
2,"(4,4)","[14.18369853, 13.84920344, 45.70641062]",0.000008,1914,5000,50,"[-0.1, 0.1]","[-50, 40]","[1, 15]"
3,"(5,5)","[12.22357828, 14.22925906, 51.8574474]",0.000005,1687,5000,50,"[-0.1, 0.1]","[-50, 40]","[1, 15]"
4,"(6,6)","[12.94084326, 11.65149118, 45.5239344]",0.000004,1922,5000,50,"[-0.1, 0.1]","[-50, 40]","[1, 15]"